name: GitHub Actions
on: [push]
jobs:
  GoTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.2'
    - run: go version
